# -*- coding: utf-8 -*-
'''Language code library'''
__author__     =  'Mark Zwaving'
__email__      =  'markzwaving@gmail.com'
__license__    =  'GNU General Public License (GPLv3)'
__copyright__  =  'Copyright (C) Mark Zwaving. All rights reserved.'
__version__    =  '0.0.2'
__status__     =  'Development'

lst = [
    ['Abkhazian', 'ab', 'abk'],
    ['Afar', 'aa', 'aar'],
    ['Afrikaans', 'af', 'afr'],
    ['Akan', 'ak', 'aka'],
    ['Albanian', 'sq', 'sqi', 'alb'],
    ['Amharic', 'am', 'amh'],
    ['Arabic', 'ar', 'ara'],
    ['Aragonese', 'an', 'arg'],
    ['Armenian', 'hy', 'arm'],
    ['Classical Armenian', 'xcl'],
    ['Western Armenian', 'hyw'],
    ['Eastern Armenian', 'hye'],
    ['Assamese', 'as', 'asm'],
    ['Avaric', 'av', 'ava'],
    ['Avestan', 'ae', 'ave'],
    ['Aymara', 'ay', 'aym'],
    ['Azerbaijani', 'az', 'aze'],
    ['Bambara', 'bm', 'bam'],
    ['Bashkir', 'ba', 'bak'],
    ['Basque', 'eu', 'eus', 'baq'],
    ['Belarusian', 'be', 'bel'],
    ['Bengali', 'bn', 'ben'],
    ['Bislama', 'bi', 'bis'],
    ['Bosnian', 'bs', 'bos'],
    ['Breton', 'br', 'bre'],
    ['Bulgarian', 'bg', 'bul'],
    ['Burmese', 'my', 'mya', 'bur'],
    ['Catalan,', 'ca', 'cat'],
    ['Chamorro', 'ch', 'cha'],
    ['Chechen', 'ce', 'che'],
    ['Chichewa', 'ny', 'nya'],
    ['Chinese', 'zh', 'zho', 'chi', 'zho'],
    ['Old Slavonic', 'cu', 'chu', 'chu'],
    ['Chuvash', 'cv', 'chv'],
    ['Cornish', 'kw', 'cor'],
    ['Corsican', 'co', 'cos'],
    ['Cree', 'cr', 'cre'],
    ['Croatian', 'hr', 'hrv'],
    ['Czech', 'cs', 'ces', 'cze'],
    ['Danish', 'da', 'dan'],
    ['Divehi', 'dv', 'div'],
    ['Dutch', 'nl', 'nld', 'dut'],
    ['Flemish', 'vls'],
    ['Dzongkha', 'dz', 'dzo'],
    ['English', 'en', 'eng'],
    ['Esperanto', 'eo', 'epo'],
    ['Estonian', 'et', 'est'],
    ['Ewe', 'ee', 'ewe'],
    ['Faroese', 'fo', 'fao'],
    ['Fijian', 'fj', 'fij'],
    ['Finnish', 'fi', 'fin'],
    ['French', 'fr', 'fra', 'fre'],
    ['Frisian', 'fy', 'fry'],
    ['Fulah', 'ff', 'ful'],
    ['Gaelic', 'gd', 'gla'],
    ['Galician', 'gl', 'glg'],
    ['Ganda', 'lg', 'lug'],
    ['Georgian', 'ka', 'kat', 'geo'],
    ['German', 'de', 'deu', 'ger'],
    ['Greek,', 'el', 'ell', 'gre'],
    ['Ancient Greek', 'grc'],
    ['Kalaallisut', 'kl', 'kal'],
    ['Guarani', 'gn', 'grn'],
    ['Gujarati', 'gu', 'guj'],
    ['Haitian Creole', 'ht', 'hat'],
    ['Hausa', 'ha', 'hau'],
    ['Hebrew', 'he', 'heb'],
    ['Modern Hebrew', 'iw'],
    ['Herero', 'hz', 'her'],
    ['Hindi', 'hi', 'hin'],
    ['Hiri Motu', 'ho', 'hmo'],
    ['Hungarian', 'hu', 'hun'],
    ['Icelandic', 'is', 'isl', 'ice'],
    ['Ido', 'io', 'ido'],
    ['Igbo', 'ig', 'ibo'],
    ['Indonesian', 'id', 'ind'],
    ['Interlingua', 'ia', 'ina'],
    ['Occidental', 'ie', 'ile'],
    ['Inuktitut', 'iu', 'iku'],
    ['Inupiaq', 'ik', 'ipk'],
    ['Irish', 'ga', 'gle'],
    ['Italian', 'it', 'ita'],
    ['Japanese', 'ja', 'jpn'],
    ['Javanese', 'jv', 'jav'],
    ['Kannada', 'kn', 'kan'],
    ['Kanuri', 'kr', 'kau'],
    ['Kashmiri', 'ks', 'kas'],
    ['Kazakh', 'kk', 'kaz'],
    ['Khmer', 'km', 'khm'],
    ['Kikuyu', 'ki', 'kik'],
    ['Kinyarwanda', 'rw', 'kin'],
    ['Kirghiz', 'ky', 'kir'],
    ['Komi', 'kv', 'kom'],
    ['Kongo', 'kg', 'kon'],
    ['Korean', 'ko', 'kor'],
    ['Kuanyama', 'kj', 'kua'],
    ['Kurdish', 'ku', 'kur'],
    ['Lao', 'lo', 'lao'],
    ['Latin', 'la', 'lat'],
    ['Latvian', 'lv', 'lav'],
    ['Limburgan, ', 'li', 'lim'],
    ['Lingala', 'ln', 'lin'],
    ['Lithuanian', 'lt', 'lit'],
    ['Luba-Katanga', 'lu', 'lub'],
    ['Luxembourgish', 'lb', 'ltz'],
    ['Macedonian', 'mk', 'mkd', 'mac'],
    ['Malagasy', 'mg', 'mlg'],
    ['Malay', 'ms', 'msa', 'may'],
    ['Malayalam', 'ml', 'mal'],
    ['Maltese', 'mt', 'mlt'],
    ['Manx', 'gv', 'glv'],
    ['Maori', 'mi', 'mri', 'mao'],
    ['Marathi', 'mr', 'mar'],
    ['Marshallese', 'mh', 'mah'],
    ['Mongolian', 'mn', 'mon'],
    ['Nauru', 'na', 'nau'],
    ['Navajo', 'nv', 'nav'],
    ['North Ndebele', 'nd', 'nde'],
    ['South Ndebele', 'nr', 'nbl'],
    ['Ndonga', 'ng', 'ndo'],
    ['Nepali', 'ne', 'nep'],
    ['Norwegian', 'no', 'nor'],
    ['Norwegian Bokmål', 'nb', 'nob'],
    ['Norwegian Nynorsk', 'nn', 'nno'],
    ['Sichuan Yi', 'ii', 'iii'],
    ['Occitan', 'oc', 'oci'],
    ['Ojibwa', 'oj', 'oji'],
    ['Oriya', 'or', 'ori'],
    ['Oromo', 'om', 'orm'],
    ['Ossetian', 'os', 'oss'],
    ['Pali', 'pi', 'pli'],
    ['Pashto', 'ps', 'pus'],
    ['Persian', 'fa', 'fas', 'per'],
    ['Polish', 'pl', 'pol'],
    ['Portuguese', 'pt', 'por'],
    ['Panjabi', 'pa', 'pan'],
    ['Quechua', 'qu', 'que'],
    ['Romanian', 'ro', 'ron', 'rum'],
    ['Romansh', 'rm', 'roh'],
    ['Rundi', 'rn', 'run'],
    ['Russian', 'ru', 'rus'],
    ['Northern Sami', 'se', 'sme'],
    ['Samoan', 'sm', 'smo'],
    ['Sango', 'sg', 'sag'],
    ['Sanskrit', 'sa', 'san'],
    ['Sardinian', 'sc', 'srd'],
    ['Serbian', 'sr', 'srp'],
    ['Shona', 'sn', 'sna'],
    ['Sindhi', 'sd', 'snd'],
    ['Sinhala, Sinhalese', 'si', 'sin'],
    ['Slovak', 'sk', 'slk', 'slo'],
    ['Slovenian', 'sl', 'slv'],
    ['Somali', 'so', 'som'],
    ['Southern Sotho', 'st', 'sot'],
    ['Spanish', 'es', 'spa'],
    ['Sundanese', 'su', 'sun'],
    ['Swahili', 'sw', 'swa'],
    ['Swati', 'ss', 'ssw'],
    ['Swedish', 'sv', 'swe'],
    ['Tagalog', 'tl', 'tgl'],
    ['Filipino', 'fil'],
    ['Tahitian', 'ty', 'tah'],
    ['Tajik', 'tg', 'tgk'],
    ['Tamil', 'ta', 'tam'],
    ['Tatar', 'tt', 'tat'],
    ['Telugu', 'te', 'tel'],
    ['Thai', 'th', 'tha'],
    ['Tibetan', 'bo', 'bod', 'tib'],
    ['Tigrinya', 'ti', 'tir'],
    ['Tonga', 'to', 'ton'],
    ['Tsonga', 'ts', 'tso'],
    ['Tswana', 'tn', 'tsn'],
    ['Turkish', 'tr', 'tur'],
    ['Turkmen', 'tk', 'tuk'],
    ['Twi', 'tw', 'twi'],
    ['Uighur', 'ug', 'uig'],
    ['Ukrainian', 'uk', 'ukr'],
    ['Urdu', 'ur', 'urd'],
    ['Uzbek', 'uz', 'uzb'],
    ['Venda', 've', 'ven'],
    ['Vietnamese', 'vi', 'vie'],
    ['Volapük', 'vo', 'vol'],
    ['Walloon', 'wa', 'wln'],
    ['Welsh', 'cy', 'cym', 'wel'],
    ['Wolof', 'wo', 'wol'],
    ['Xhosa', 'xh', 'xho'],
    ['Yiddish', 'yi', 'yid'],
    ['Yoruba', 'yo', 'yor'],
    ['Zhuang', 'za', 'zha'],
    ['Zulu', 'zu', 'zul']
]

def is_available(lang):
    lang = lang.lower()
    for l in lst:
        for c in l: # Search for lang
            if c.lower() == lang: # Lang/code found
                return True

    return False

def get(lang):
    lang = lang.lower()
    for l in lst:
        for c in l: # Search for lang
            if lang == c.lower(): # Lang/code found
                return l[0] # Return language

    return 'English' # Default
